### ISSUE TITLE
run sample-test failed on avd with API 19

### ISSUE THREAD

**Issue by chenDoInG** [macacajs/macaca-android#65]
I use avd with API 19 to run sample-test. When send 'drag' command to server the test will fail. 
`
>> responseHandler.js:11:12 [master] pid:19111 Recieve HTTP Request from Client[2017-05-27 16:27:28]: method: POST url: /wd/hub/session/00f4b0e8-796e-4f3d-875d-ad208859eed7/actions, jsonBody: {"actions":[{"duration":"50.0","type":"drag","fromX":"200.0","toX":"200.0","fromY":"420.0","steps":"100","toY":"10.0"}]}
>> proxy.js:55:14 [master] pid:19111 Proxy: /wd/hub/session/00f4b0e8-796e-4f3d-875d-ad208859eed7/actions:POST to http://127.0.0.1:9001/wd/hub/session/00f4b0e8-796e-4f3d-875d-ad208859eed7/actions:POST with body: {"actions":[{"duration":"50.0","type":"drag","fromX":"200.0","toX":"200.0","fromY":"420.0","steps":"100","toY":"10.0"}]}
>> proxy.js:83:20 [master] pid:19111 Got response with status 200: {"sessionId":"00f4b0e8-796e-4f3d-875d-ad208859eed7","status":13,"value":"An unknown server-side error occurred while processing the command."}
>> session.js:107:14 [master] pid:19111 Send HTTP Respone to Client[2017-05-27 16:27:28]: {"sessionId":"00f4b0e8-796e-4f3d-875d-ad208859eed7","status":13,"value":"\"An unknown server-side error occurred while processing the command.\""}
`

**Comment by xudafeng** [comment]
@chenDoInG 更新最新wd.java 应该是请求的格式不对

**Comment by kyowang** [comment]
@chenDoInG 最新的wd.java里面drag的参数个数根据uiautomator里面的参数align了。
[{"duration":"50.0","type":"drag","fromX":"200.0","toX":"200.0","fromY":"420.0","steps":"100","toY":"10.0"}]}
变成了只有steps，没有duration了。
你更新到最新的wd.java即可。
