### ISSUE TITLE
Why the IME(android_unicode) was removed from macaca-android

### ISSUE THREAD

**Issue by kyowang** [macacajs/macaca-android#66]
Hi @xudafeng 
I notised that there was a commit on 2017-05-13 in which 
the IME was removed.
and so now the chinese characters are not supported any more.
Is there any reason for this change? or will it be added back in the future?

```
Author: xudafeng <xudafeng@126.com>  2017-05-13 00:27:14
Committer: xudafeng <xudafeng@126.com>  2017-05-13 00:27:14
Parent: e89d77b640bf9f80623b5d432b88e248e357b15a (fix source router)
Child:  eef969290bf65b1d2b0fb7b43a347fe2f5ca5e3c (handle waitfor activity (#62))
Branches: master, remotes/origin/master
 fix IME
```

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-android/pull/67
