### ISSUE TITLE
降级安装1.1.34 macaca-android失败，新版本没问题

### ISSUE THREAD

**Issue by wilischan** [macacajs/macaca-android#68]
npm i macaca-android@1.1.34 -g
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> unlock-apk@0.1.16 install /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk
> node ./script/build.js

JAVA_HOME is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home
Buildfile: /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/build.xml

BUILD FAILED
/usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/build.xml:81: Cannot find /Users/wilis/Library/Android/sdk/tools/ant/build.xml imported from /usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/build.xml

Total time: 0 seconds
Error: build failed
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/macaca-android/node_modules/ant-build/lib/ant-build.js:111:16)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
/usr/local/lib/node_modules/macaca-android/node_modules/unlock-apk/script/build.js:28
    throw e;
    ^

Error: build failed
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/macaca-android/node_modules/ant-build/lib/ant-build.js:111:16)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unlock-apk@0.1.16 install: `node ./script/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unlock-apk@0.1.16 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wilis/.npm/_logs/2017-06-27T07_10_13_617Z-debug.log

**Comment by xudafeng** [comment]
不要再使用1.x
