### ISSUE TITLE
File access issue

### ISSUE THREAD

**Issue by SamuelZhaoY** [macacajs/macaca-android#75]
<img width="812" alt="2017-12-14 5 52 18" src="https://user-images.githubusercontent.com/8198256/33992500-d637f736-e10d-11e7-9c53-d281f9f95eb1.png">
<img width="1273" alt="2017-12-14 5 52 26" src="https://user-images.githubusercontent.com/8198256/33992506-dc271dca-e10d-11e7-924a-a1b34ffe49df.png">

**Comment by SamuelZhaoY** [comment]
Can we change another directory for this?  instead of using Environment.getDataDirectory() + File.separator + "local" + File.separator + "tmp" + File.separator + dumpFileName

**Comment by qichuan** [comment]
We can use Environment.getExternalStorageDirectory() or context.getExternalFilesDir, these are external/shared directories that can be accessed without explicit chmod operation.

**Comment by SamuelZhaoY** [comment]
@qichuan 👍 let's try it.  You can use the XiaoMi device to verify it

**Comment by SamuelZhaoY** [comment]
细化一下问题， 现在有好几个不同case：

- [ ] 在小米3 OS 4.4 中 启动NoSmoke 后会不断restart：
<img width="1168" alt="2017-12-27 5 53 54" src="https://user-images.githubusercontent.com/8198256/34378031-f441bb92-eb2e-11e7-9cdb-31e646973b3d.png">
- [ ] 正常运行的情况下也会有adb 报错：
<img width="885" alt="2" src="https://user-images.githubusercontent.com/8198256/34377991-bf1ecfa4-eb2e-11e7-9513-9586971f60be.png">
- [ ] 在linux 服务器上测试的部分安卓特定设备会稳定crash (security manager exception):
<img width="1172" alt="1" src="https://user-images.githubusercontent.com/8198256/34377987-bb094534-eb2e-11e7-8dc6-555e6da61df2.png">

**Comment by SamuelZhaoY** [comment]
问题1 修复：macacajs-adb 代码未更新
问题2 修复:  controller.js 数据结构兼容问题

**Comment by SamuelZhaoY** [comment]
问题3 修复： 梳理文件权限
