### ISSUE TITLE
安装macaca-android新版本，xml2map@^1.0.2找不到版本

### ISSUE THREAD

**Issue by 1962029115** [macacajs/macaca-android#92]
环境：node :v18.13.0 npm:8.19.3;windows10

C:\Users\admin>npm install macaca-android
npm ERR! code ETARGET
npm ERR! notarget No matching version found for xml2map@^1.0.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Local\npm-cache\_logs\2023-02-06T10_47_55_876Z-debug-0.log

2.0.12版本以及一下，没问题。库资源里面也搜索不到1.0.2版本；xml2map2才有1.0.2版本。
各位大佬，帮忙看一下

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-android/pull/93
